[2024-10-05T09:14:52.649+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T09:14:52.672+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline.youtube_extration manual__2024-10-05T09:14:50.548720+00:00 [queued]>
[2024-10-05T09:14:52.687+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline.youtube_extration manual__2024-10-05T09:14:50.548720+00:00 [queued]>
[2024-10-05T09:14:52.689+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-05T09:14:52.706+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): youtube_extration> on 2024-10-05 09:14:50.548720+00:00
[2024-10-05T09:14:52.714+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2024-10-05T09:14:52.720+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_pipeline', 'youtube_extration', 'manual__2024-10-05T09:14:50.548720+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/youtube_dag.py', '--cfg-path', '/tmp/tmpy34sd0dh']
[2024-10-05T09:14:52.725+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask youtube_extration
[2024-10-05T09:14:52.786+0000] {task_command.py:467} INFO - Running <TaskInstance: youtube_pipeline.youtube_extration manual__2024-10-05T09:14:50.548720+00:00 [running]> on host 4715c926778f
[2024-10-05T09:14:52.876+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Haziq' AIRFLOW_CTX_DAG_ID='youtube_pipeline' AIRFLOW_CTX_TASK_ID='youtube_extration' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T09:14:50.548720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-05T09:14:50.548720+00:00'
[2024-10-05T09:14:52.880+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T09:14:52.906+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-10-05T09:14:54.952+0000] {logging_mixin.py:190} INFO - playlist id isUUX6OQ3DkcsbYNE6H8uQQuVA
[2024-10-05T09:25:49.623+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-10-05T09:25:49.628+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-05T09:25:49.643+0000] {process_utils.py:132} INFO - Sending 15 to group 81. PIDs of all processes in the group: [81]
[2024-10-05T09:25:49.645+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 81
[2024-10-05T09:25:49.647+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-05T09:25:49.685+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T09:25:49.740+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=81, status='terminated', exitcode=0, started='09:14:51') (81) terminated with exit code 0
