[2024-10-03T11:57:13.779+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T11:57:13.802+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline.s3_upload manual__2024-10-03T11:56:43.895933+00:00 [queued]>
[2024-10-03T11:57:13.821+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline.s3_upload manual__2024-10-03T11:56:43.895933+00:00 [queued]>
[2024-10-03T11:57:13.824+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-03T11:57:13.843+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-10-03 11:56:43.895933+00:00
[2024-10-03T11:57:13.851+0000] {standard_task_runner.py:72} INFO - Started process 80 to run task
[2024-10-03T11:57:13.855+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_pipeline', 's3_upload', 'manual__2024-10-03T11:56:43.895933+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/youtube_dag.py', '--cfg-path', '/tmp/tmpsgs7y98i']
[2024-10-03T11:57:13.860+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask s3_upload
[2024-10-03T11:57:13.927+0000] {task_command.py:467} INFO - Running <TaskInstance: youtube_pipeline.s3_upload manual__2024-10-03T11:56:43.895933+00:00 [running]> on host da25242427ee
[2024-10-03T11:57:14.029+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Haziq' AIRFLOW_CTX_DAG_ID='youtube_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T11:56:43.895933+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T11:56:43.895933+00:00'
[2024-10-03T11:57:14.034+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T11:57:14.063+0000] {logging_mixin.py:190} INFO - connected successfully to s3
[2024-10-03T11:57:17.992+0000] {logging_mixin.py:190} INFO - bucket already exist
[2024-10-03T11:57:17.995+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline_youtube.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path,AWS_BUCKET_NAME)
TypeError: upload_to_s3() missing 1 required positional argument: 'file_name'
[2024-10-03T11:57:18.020+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=youtube_pipeline, task_id=s3_upload, run_id=manual__2024-10-03T11:56:43.895933+00:00, execution_date=20241003T115643, start_date=20241003T115713, end_date=20241003T115718
[2024-10-03T11:57:18.047+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T11:57:18.051+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 53 for task s3_upload (upload_to_s3() missing 1 required positional argument: 'file_name'; 80)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline_youtube.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path,AWS_BUCKET_NAME)
TypeError: upload_to_s3() missing 1 required positional argument: 'file_name'
[2024-10-03T11:57:18.103+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T11:57:18.126+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T11:57:18.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
